### ISSUE TITLE
Use of <em> - perhaps use quotes instead

### ISSUE THREAD

**Issue by drgrigg** [laurakwriting/anna-sewell_black-beauty#2]
There are three instances where `<em>` is used in the text, but in each case these instances are not really examples of emphasis in speech, but quoted names (even if the page scans have them in italic).

I would be tempted to remove the tags and use double quotes:

Eg: 
`and named me <em>Black Auster</em>`  (Chapter 24)

I think this would be better as:

`and named me “Black Auster”`

Same for the other two examples in chapters 39 and 41.

**Comment by laurakwriting** [comment]
I agree - changed <em> tags to quotes
