### ISSUE TITLE
Content.opf : remove unused WIKI and NACOAF entries for artist

### ISSUE THREAD

**Issue by drgrigg** [laurakwriting/anna-sewell_black-beauty#4]
You should remove the meta entries containing these dummy entries, since the artist does not have a Wikipedia page or a Library of Congress identifier:

COVER_ARTIST_WIKI_URL
COVER_ARTIST_NACOAF_URL

Just take out the whole line with the meta tags containing these.

**Comment by laurakwriting** [comment]
Sounds good - done
